### ISSUE TITLE
Invalid Binance API key provided

### ISSUE THREAD

**Issue by millergits** [0x78f1935/PyNance-Webinterface#6]
I did my best to follow the instructions ... I updated the .env.production file with my Binance API Key & Secret and I used docker-compose to build. After waiting for everything to come up, I visit 127.0.0.1:1337 and run through the wizard. But every time I enter the master password I get the following error:

"Invalid Binance API key provided"

I triple checked my Binance API Key restrictions and the key/secret in the .env.production file. Everything looks right. I've tried over and over, even opening a new binance account with new keys ... but I can't seem to make it work.

Any tips on how I can get things working with my Binance key/secret???

Thank you!

**Comment by 0x78f1935** [comment]
Hi!

Thank you for your message, Please make sure of the following:

- No trailing spaces, matter in fact, get rid of all spaces in your production/development environment
- No quotes around your API key
- Make sure your Binance token has the following permissions: `Reading, Spot & Margin Trading and Futures` for all functionality
- Make sure PyNance picks up the correct environment file. backend/config/__init__.py. Disable `DEBUG` to use the production file, If True it uses the development file.
- Make sure you have restricted the API key to the right IP address.

I hope one of the following tips help you in the right direction, Let me know if it worked!

**Comment by 0x78f1935** [comment]
Closing due inactivity. Feel free re-open again when needed.
